Repository OpenNebula/terraform-provider-opennebula, pull requests merged in 2019-12, with the labels that each got.

#7 Fix setting of cluster id on Virtual Network creation
  opennebula/resource_opennebula_virtual_network.go
Labels: size/XS

#9 Bub1 bug5
  .coveralls.yml
  .travis/tests/terraform.sh
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  vendor/modules.txt
Labels: dependencies, size/M

#11 B-2: Fix optional value update
  opennebula/resource_opennebula_group.go
  opennebula/resource_opennebula_image.go
  opennebula/resource_opennebula_security_group.go
  opennebula/resource_opennebula_virtual_data_center.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/resource_opennebula_virtual_network.go
  opennebula/resource_opennebula_virtual_network_test.go
Labels: size/M

#12 Update Changelog with missing fixed issues
  CHANGELOG.md
Labels: size/XS

#14 R/Virtual_Machine: Add deprecated flag to instance
  CHANGELOG.md
  opennebula/resource_opennebula_virtual_machine.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS
