Repository OpenNebula/terraform-provider-opennebula, pull requests merged in 2020-02, with the labels that each got.

#21 F 16
  CHANGELOG.md
  opennebula/data_opennebula_template_vm_group.go
  opennebula/provider.go
  opennebula/resource_opennebula_template_vm_group.go
  opennebula/resource_opennebula_template_vm_group_test.go
  opennebula/resource_opennebula_virtual_machine.go
  website/docs/d/virtual_machine_group.html.markdown
  website/docs/r/virtual_machine.html.markdown
  website/docs/r/virtual_machine_group.html.markdown
  website/opennebula.erb
Labels: documentation, new-resource, size/XL

#13 Align goca and override context in the VM
  CHANGELOG.md
  go.mod
  go.sum
  opennebula/helpers.go
  opennebula/permissions.go
  opennebula/resource_opennebula_group.go
  opennebula/resource_opennebula_image.go
  opennebula/resource_opennebula_image_test.go
  opennebula/resource_opennebula_security_group.go
  opennebula/resource_opennebula_template.go
  opennebula/resource_opennebula_template_test.go
  opennebula/resource_opennebula_template_vm_group.go
  opennebula/resource_opennebula_template_vm_group_test.go
  opennebula/resource_opennebula_virtual_data_center.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/resource_opennebula_virtual_network.go
  opennebula/resource_opennebula_virtual_network_test.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/datastore.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/document.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/dynamic/dyntemplate.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/filter.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/hook.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/image.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/marketplace.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/marketplaceapp.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/schemas/shared/permissions.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/securitygroup.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/template.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/virtualnetwork.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/virtualrouter.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/vm.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/vmgroup.go
  vendor/github.com/OpenNebula/one/src/oca/go/src/goca/vntemplate.go
  vendor/github.com/kolo/xmlrpc/client.go
  vendor/github.com/kylelemons/godebug/LICENSE
  vendor/github.com/kylelemons/godebug/diff/diff.go
  vendor/github.com/kylelemons/godebug/pretty/.gitignore
  vendor/github.com/kylelemons/godebug/pretty/doc.go
  vendor/github.com/kylelemons/godebug/pretty/public.go
  vendor/github.com/kylelemons/godebug/pretty/reflect.go
  vendor/github.com/kylelemons/godebug/pretty/structure.go
  vendor/modules.txt
Labels: dependencies, enhancement, size/XXL

#24 enhance template schema
  CHANGELOG.md
  opennebula/resource_opennebula_template.go
  opennebula/resource_opennebula_template_test.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/shared_schemas.go
  website/docs/r/template.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, enhancement, size/XXL
