Repository OpenNebula/terraform-provider-opennebula, pull requests merged in 2020-10, with the labels that each got.

#55 Update README.md
  README.md
Labels: documentation, size/S

#59 Allow update of VM disks
  opennebula/helpers_vm.go
  opennebula/resource_opennebula_image.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/shared_schemas.go
Labels: enhancement, provider, size/XL

#62 Use goca acl methods
  go.mod
  go.sum
  opennebula/resource_opennebula_acl.go
  opennebula/resource_opennebula_acl_test.go
Labels: provider, size/M

#75 F 71
  CHANGELOG.md
  opennebula/helpers_vm.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/shared_schemas.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement, provider

#61 refact goca error handling
  opennebula/helpers.go
  opennebula/resource_opennebula_group.go
  opennebula/resource_opennebula_image.go
  opennebula/resource_opennebula_security_group.go
  opennebula/resource_opennebula_template.go
  opennebula/resource_opennebula_template_vm_group.go
  opennebula/resource_opennebula_virtual_data_center.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_network.go
Labels: enhancement, provider, size/L
