Repository OpenNebula/terraform-provider-opennebula, pull requests merged in 2020-06, with the labels that each got.

#38 Update TravisCI configuration to use ONE 5.12
  .travis.yml
  .travis/before_script/oned.sh
  CHANGELOG.md
  README.md
Labels: size/S

#39 F 36
  CHANGELOG.md
  opennebula/resource_opennebula_image.go
  opennebula/resource_opennebula_image_test.go
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
  website/docs/r/image.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/S

#45 B-43: Resource/Virtual_machine: Fix error management
  opennebula/resource_opennebula_virtual_machine.go
  opennebula/resource_opennebula_virtual_machine_test.go
Labels: size/XS

#44 B-42: Add Context on flatten template
  opennebula/resource_opennebula_template_test.go
  opennebula/resource_opennebula_virtual_machine_test.go
  opennebula/shared_schemas.go
Labels: size/S
