Repository OpenNebula/terraform-provider-opennebula, pull requests merged in 2022-05, with the labels that each got.

#238 [resource][virtual network] fix clusters attribute documentation
  website/docs/r/virtual_network.html.markdown
Labels: documentation

#237 introduce FEATURES section for templates
  CHANGELOG.md
  opennebula/resource_opennebula_template.go
  opennebula/resource_opennebula_template_test.go
  opennebula/shared_schemas.go
  website/docs/r/template.html.markdown
Labels: enhancement

#262 Update CI from `6.2` to `6.4`
  .ci_scripts/terraform.sh
  .github/scripts/lint.sh
  .github/scripts/oned.sh
  .github/workflows/ci.yaml
  .gitignore
  .travis.yml
  README.md
Labels: github/action

#258 Fix VN test for OpenNebula 6.4
  opennebula/resource_opennebula_virtual_network_test.go
Labels: enhancement, needs-ci-6_2-fix
